# Generated by Django 5.1.3 on 2024-11-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('author', 'author'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
