# Generated by Django 5.1.3 on 2024-11-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
